"""Add giver_name to giving

Revision ID: 14c1e87d703c
Revises: b58e936fb15d
Create Date: 2026-02-23 18:49:29.345407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c1e87d703c'
down_revision = 'b58e936fb15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giver_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.drop_column('giver_name')

    # ### end Alembic commands ###
